import {useNavigate} from "react-router-dom";

const LandingPage = () => {
    const navigate = useNavigate();
    const handelClick = () => {
        navigate("/demo");
    }
    return(
        <div className={"h-screen w-screen bg-gray-200"}>
            <h1
                className={"font-cinzel text-center pt-80 text-4xl"}
            >
                ThrorMap (In development)
            </h1>
            <p className={"px-60 mt-8 font-raleway font-bold"}>
                We advance people’s rights to their freedom of information by offering a standardized and consolidated way to access all publicly available information generated by the U.S. government. We do so by providing  a conceptual data lake that covers over 400 government databases and offer users a custom, single API endpoint to this valuable, industry changing sea of information.
            </p>

            <p className={"px-60 mt-8 font-raleway font-bold"}>
                The sample below is a graphical query builder. ThrorMap provides two ways of accessing our service, graphical user interface hosted on this website and direct HTTP API access.
            </p>

            <div className={"w-screen flex justify-center mt-8"}>
                <button
                    className={"border-2 border-gray-600 py-2 px-6 rounded-md hover:bg-gray-600 hover:text-amber-50 font-lora"}
                    onClick={handelClick}
                >
                    Sample
                </button>
            </div>
        </div>
    )
}

export default LandingPage;